### 1. Write a Python Program to Add Two Matrices?

In [3]:
import numpy as np

In [8]:
mat1=np.matrix([[2,3,4,5],[5,6,7,8],[2,4,6,8]])
mat2=np.matrix([[2,3,4,4],[5,1,7,8],[9,4,4,8]])
print(mat1+mat2)

[[ 4  6  8  9]
 [10  7 14 16]
 [11  8 10 16]]


### 2. Write a Python Program to Multiply Two Matrices?

In [13]:
mat1=np.matrix([[2,3,4,5],[5,6,7,8],[2,4,6,8],[2,3,4,4]])
mat2=np.matrix([[2,3,4,4],[5,1,7,8],[9,4,4,8],[2,4,6,8]])
mat1*mat2

matrix([[ 65,  45,  75, 104],
        [119,  81, 138, 188],
        [ 94,  66, 108, 152],
        [ 63,  41,  69,  96]])

### 3. Write a Python Program to Transpose a Matrix?

In [20]:
print("original matrix=\n",mat1)
print("transpose of matrix=\n",mat1.T)

original matrix=
 [[2 3 4 5]
 [5 6 7 8]
 [2 4 6 8]
 [2 3 4 4]]
transpose of matrix=
 [[2 5 2 2]
 [3 6 4 3]
 [4 7 6 4]
 [5 8 8 4]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [8]:
sentence = input("Enter a sentence: ")

words=[word.lower() for word in sentence.split(" ")]
words.sort()
print("\nthe sorted words in alphabetical order is:\n")
for word in words:
    print(word)


Enter a sentence: hello sir give me full marks for this assignment

the sorted words in alphabetical order is:

assignment
for
full
give
hello
marks
me
sir
this


### 5. Write a Python Program to Remove Punctuation From a String?

In [14]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

sentence = "Hello!!!, he said ---and went."

# removing punctuation from the string
no_punctuation = " "
for i in my_str:
    if i not in punctuations:
        no_punctuation = no_punctuation + i

# display the unpunctuated string
print(no_punctuation)

 Hello he said and went
